
import { GoogleGenAI } from "@google/genai";

const sleep = (ms: number) => new Promise(res => setTimeout(res, ms));

async function withRetry<T>(fn: () => Promise<T>, retries = 3, delay = 2000): Promise<T> {
  try {
    return await fn();
  } catch (error: any) {
    const errorMessage = error?.message || "";
    const status = error?.status || (error?.code ? parseInt(error.code) : 0);
    const isRateLimit = errorMessage.includes('429') || status === 429 || status === 503;

    if (retries > 0 && isRateLimit) {
      await sleep(delay);
      return withRetry(fn, retries - 1, delay * 2);
    }
    throw error;
  }
}

const getApiKey = () => {
  const key = import.meta.env.VITE_GEMINI_API_KEY || import.meta.env.GEMINI_API_KEY;
  if (!key) {
    console.warn("VITE_GEMINI_API_KEY is not set. AI features will not work.");
  }
  return key || 'MISSING_API_KEY'; // Prevent absolute crash but calls will fail
};

export const generateChargingAdvice = async (userPrompt: string) => {
  return withRetry(async () => {
    const ai = new GoogleGenAI({ apiKey: getApiKey() });
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Du är en expert på elbilsladdning hos Clean Charge AB. Svara kortfattat och professionellt på svenska. Fråga: ${userPrompt}`,
    });
    return response.text;
  });
};

// New: Generate market insights with search grounding, wrapped in retry logic
export const generateMarketInsights = async () => {
  return withRetry(async () => {
    const ai = new GoogleGenAI({ apiKey: getApiKey() });
    return await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: "Ge en professionell och dagsaktuell sammanfattning (på svenska) om de senaste nyheterna, testerna och trenderna för elbilsladdning i Sverige 2024/2025. Inkludera information om märken som Easee, Zaptec, Charge Amps och Wallbox, samt betallösningar som Monta och Spirii. VIKTIGT: Använd ingen markdown-formatering (inga stjärnor eller hashtaggar), svara med ren text.",
      config: {
        tools: [{ googleSearch: {} }],
      },
    });
  });
};

// New: Create a stateful chat session for the widget with Google Search enabled
export const createChatSession = () => {
  const ai = new GoogleGenAI({ apiKey: getApiKey() });
  return ai.chats.create({
    model: 'gemini-3-flash-preview',
    config: {
      tools: [{ googleSearch: {} }],
      systemInstruction: `Du är "Charge Bot", en hjälpsam och kunnig AI-assistent för företaget Clean Charge AB.
      
      Ditt uppdrag är att hjälpa besökare med frågor om:
      1. Laddboxar: Vi säljer främst Zaptec (Go och Pro) samt Easee (Charge Lite). Vi har även Autel för snabbladdning.
      2. Installation: Vi erbjuder installation i hela Sverige.
      3. Grön Teknik: Privatpersoner får 50% skatteavdrag direkt på fakturan.
      4. Mjukvara: Vi använder Monta för betalning, styrning och lastbalansering.
      5. Företag/BRF: Vi erbjuder helhetslösningar, betalsystem och administration.
      
      Du har tillgång till Google Sök. Använd det för att hitta aktuell information om elbilsladdning, konkurrenter eller nyheter om du inte vet svaret direkt.
      
      Tonläge: Professionellt, trevligt, hjälpsamt och kortfattat. Svara alltid på svenska.
      Om du inte vet svaret, be kunden kontakta supporten på 019-760 42 90 eller info@cleancharge.se.
      
      Viktigt: Du får inte hitta på priser som inte finns i din kunskap, hänvisa då till offertförfrågan.`,
    },
  });
};

// Fix: Implemented generateVisualConcept using gemini-2.5-flash-image for high-quality image generation
export const generateVisualConcept = async (prompt: string) => {
  return withRetry(async () => {
    const ai = new GoogleGenAI({ apiKey: getApiKey() });
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: prompt }]
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9",
        }
      }
    });

    // Iterate through all parts to find the image part as per guidelines
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by the model.");
  });
};

// Fix: Implemented cloneImage for image-to-image editing using gemini-2.5-flash-image
export const cloneImage = async (base64Data: string, mimeType: string, prompt: string) => {
  return withRetry(async () => {
    const ai = new GoogleGenAI({ apiKey: getApiKey() });
    
    // Strip data URL prefix if present to extract pure base64 data
    const cleanBase64 = base64Data.includes('base64,') 
      ? base64Data.split('base64,')[1] 
      : base64Data;
    
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9",
        }
      }
    });

    // Find the image part in the response candidates
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by the model during cloning.");
  });
};
